"""empty message

Revision ID: 580ccece1db4
Revises: c9aaa6b6ccda
Create Date: 2025-06-30 11:46:48.848410

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '580ccece1db4'
down_revision: Union[str, Sequence[str], None] = 'c9aaa6b6ccda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['transaction'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
