"""empty message

Revision ID: c6402b978ad8
Revises: 30652c8e636b
Create Date: 2025-06-26 12:01:26.930770

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6402b978ad8'
down_revision: Union[str, Sequence[str], None] = '30652c8e636b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_user_id_id_key'), 'accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('accounts_user_id_id_key'), 'accounts', ['user_id', 'id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
