"""empty message

Revision ID: ce15818b1634
Revises: fae37b69244e
Create Date: 2025-06-30 10:43:55.638045

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ce15818b1634'
down_revision: Union[str, Sequence[str], None] = 'fae37b69244e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
